ERROR - 2024-09-21 12:30:44 --> ErrorException: pg_query(): Query failed: ERROR:  ya existe la columna «precio_3» en la relación «producto» in C:\xampp\htdocs\dfpyme\system\Database\Postgre\Connection.php:135
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135)
#1 C:\xampp\htdocs\dfpyme\system\Database\Postgre\Connection.php(135): pg_query(Resource id #177, 'ALTER TABLE "pr...')
#2 C:\xampp\htdocs\dfpyme\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('ALTER TABLE "pr...')
#3 C:\xampp\htdocs\dfpyme\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('ALTER TABLE "pr...')
#4 C:\xampp\htdocs\dfpyme\system\Database\Forge.php(722): CodeIgniter\Database\BaseConnection->query('ALTER TABLE "pr...')
#5 C:\xampp\htdocs\dfpyme\app\Database\Migrations\2024-09-21-025053_AddPrecio3ToProductos.php(13): CodeIgniter\Database\Forge->addColumn('producto', Array)
#6 C:\xampp\htdocs\dfpyme\system\Database\MigrationRunner.php(863): App\Database\Migrations\AddPrecio3ToProductos->up()
#7 C:\xampp\htdocs\dfpyme\system\Database\MigrationRunner.php(186): CodeIgniter\Database\MigrationRunner->migrate('up', Object(stdClass))
#8 C:\xampp\htdocs\dfpyme\system\Commands\Database\Migrate.php(84): CodeIgniter\Database\MigrationRunner->latest(NULL)
#9 C:\xampp\htdocs\dfpyme\system\CLI\Commands.php(63): CodeIgniter\Commands\Database\Migrate->run(Array)
#10 C:\xampp\htdocs\dfpyme\system\CLI\CommandRunner.php(70): CodeIgniter\CLI\Commands->run('migrate', Array)
#11 C:\xampp\htdocs\dfpyme\system\CLI\CommandRunner.php(56): CodeIgniter\CLI\CommandRunner->index(Array)
#12 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(830): CodeIgniter\CLI\CommandRunner->_remap('index', 'migrate')
#13 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(CodeIgniter\CLI\CommandRunner))
#14 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#15 C:\xampp\htdocs\dfpyme\system\CLI\Console.php(48): CodeIgniter\CodeIgniter->run()
#16 C:\xampp\htdocs\dfpyme\spark(63): CodeIgniter\CLI\Console->run()
#17 {main}
ERROR - 2024-09-21 18:23:25 --> ErrorException: pg_query(): Query failed: ERROR:  ya existe la columna «precio_3» en la relación «producto» in C:\xampp\htdocs\dfpyme\system\Database\Postgre\Connection.php:135
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135)
#1 C:\xampp\htdocs\dfpyme\system\Database\Postgre\Connection.php(135): pg_query(Resource id #177, 'ALTER TABLE "pr...')
#2 C:\xampp\htdocs\dfpyme\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('ALTER TABLE "pr...')
#3 C:\xampp\htdocs\dfpyme\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('ALTER TABLE "pr...')
#4 C:\xampp\htdocs\dfpyme\system\Database\Forge.php(722): CodeIgniter\Database\BaseConnection->query('ALTER TABLE "pr...')
#5 C:\xampp\htdocs\dfpyme\app\Database\Migrations\2024-09-21-025053_AddPrecio3ToProductos.php(13): CodeIgniter\Database\Forge->addColumn('producto', Array)
#6 C:\xampp\htdocs\dfpyme\system\Database\MigrationRunner.php(863): App\Database\Migrations\AddPrecio3ToProductos->up()
#7 C:\xampp\htdocs\dfpyme\system\Database\MigrationRunner.php(186): CodeIgniter\Database\MigrationRunner->migrate('up', Object(stdClass))
#8 C:\xampp\htdocs\dfpyme\system\Commands\Database\Migrate.php(84): CodeIgniter\Database\MigrationRunner->latest(NULL)
#9 C:\xampp\htdocs\dfpyme\system\CLI\Commands.php(63): CodeIgniter\Commands\Database\Migrate->run(Array)
#10 C:\xampp\htdocs\dfpyme\system\CLI\CommandRunner.php(70): CodeIgniter\CLI\Commands->run('migrate', Array)
#11 C:\xampp\htdocs\dfpyme\system\CLI\CommandRunner.php(56): CodeIgniter\CLI\CommandRunner->index(Array)
#12 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(830): CodeIgniter\CLI\CommandRunner->_remap('index', 'migrate')
#13 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(CodeIgniter\CLI\CommandRunner))
#14 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#15 C:\xampp\htdocs\dfpyme\system\CLI\Console.php(48): CodeIgniter\CodeIgniter->run()
#16 C:\xampp\htdocs\dfpyme\spark(63): CodeIgniter\CLI\Console->run()
#17 {main}
ERROR - 2024-09-21 18:52:06 --> ErrorException: pg_query(): Query failed: ERROR:  ya existe la columna «precio_3» en la relación «producto» in C:\xampp\htdocs\dfpyme\system\Database\Postgre\Connection.php:135
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135)
#1 C:\xampp\htdocs\dfpyme\system\Database\Postgre\Connection.php(135): pg_query(Resource id #177, 'ALTER TABLE "pr...')
#2 C:\xampp\htdocs\dfpyme\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('ALTER TABLE "pr...')
#3 C:\xampp\htdocs\dfpyme\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('ALTER TABLE "pr...')
#4 C:\xampp\htdocs\dfpyme\system\Database\Forge.php(722): CodeIgniter\Database\BaseConnection->query('ALTER TABLE "pr...')
#5 C:\xampp\htdocs\dfpyme\app\Database\Migrations\2024-09-21-025053_AddPrecio3ToProductos.php(13): CodeIgniter\Database\Forge->addColumn('producto', Array)
#6 C:\xampp\htdocs\dfpyme\system\Database\MigrationRunner.php(863): App\Database\Migrations\AddPrecio3ToProductos->up()
#7 C:\xampp\htdocs\dfpyme\system\Database\MigrationRunner.php(186): CodeIgniter\Database\MigrationRunner->migrate('up', Object(stdClass))
#8 C:\xampp\htdocs\dfpyme\system\Commands\Database\Migrate.php(84): CodeIgniter\Database\MigrationRunner->latest(NULL)
#9 C:\xampp\htdocs\dfpyme\system\CLI\Commands.php(63): CodeIgniter\Commands\Database\Migrate->run(Array)
#10 C:\xampp\htdocs\dfpyme\system\CLI\CommandRunner.php(70): CodeIgniter\CLI\Commands->run('migrate', Array)
#11 C:\xampp\htdocs\dfpyme\system\CLI\CommandRunner.php(56): CodeIgniter\CLI\CommandRunner->index(Array)
#12 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(830): CodeIgniter\CLI\CommandRunner->_remap('index', 'migrate')
#13 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(CodeIgniter\CLI\CommandRunner))
#14 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#15 C:\xampp\htdocs\dfpyme\system\CLI\Console.php(48): CodeIgniter\CodeIgniter->run()
#16 C:\xampp\htdocs\dfpyme\spark(63): CodeIgniter\CLI\Console->run()
#17 {main}
ERROR - 2024-09-21 18:54:19 --> ErrorException: pg_query(): Query failed: ERROR:  ya existe la columna «precio_3» en la relación «producto» in C:\xampp\htdocs\dfpyme\system\Database\Postgre\Connection.php:135
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135)
#1 C:\xampp\htdocs\dfpyme\system\Database\Postgre\Connection.php(135): pg_query(Resource id #177, 'ALTER TABLE "pr...')
#2 C:\xampp\htdocs\dfpyme\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('ALTER TABLE "pr...')
#3 C:\xampp\htdocs\dfpyme\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('ALTER TABLE "pr...')
#4 C:\xampp\htdocs\dfpyme\system\Database\Forge.php(722): CodeIgniter\Database\BaseConnection->query('ALTER TABLE "pr...')
#5 C:\xampp\htdocs\dfpyme\app\Database\Migrations\2024-09-21-025053_AddPrecio3ToProductos.php(13): CodeIgniter\Database\Forge->addColumn('producto', Array)
#6 C:\xampp\htdocs\dfpyme\system\Database\MigrationRunner.php(863): App\Database\Migrations\AddPrecio3ToProductos->up()
#7 C:\xampp\htdocs\dfpyme\system\Database\MigrationRunner.php(186): CodeIgniter\Database\MigrationRunner->migrate('up', Object(stdClass))
#8 C:\xampp\htdocs\dfpyme\system\Commands\Database\Migrate.php(84): CodeIgniter\Database\MigrationRunner->latest(NULL)
#9 C:\xampp\htdocs\dfpyme\system\CLI\Commands.php(63): CodeIgniter\Commands\Database\Migrate->run(Array)
#10 C:\xampp\htdocs\dfpyme\system\CLI\CommandRunner.php(70): CodeIgniter\CLI\Commands->run('migrate', Array)
#11 C:\xampp\htdocs\dfpyme\system\CLI\CommandRunner.php(56): CodeIgniter\CLI\CommandRunner->index(Array)
#12 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(830): CodeIgniter\CLI\CommandRunner->_remap('index', 'migrate')
#13 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(CodeIgniter\CLI\CommandRunner))
#14 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#15 C:\xampp\htdocs\dfpyme\system\CLI\Console.php(48): CodeIgniter\CodeIgniter->run()
#16 C:\xampp\htdocs\dfpyme\spark(63): CodeIgniter\CLI\Console->run()
#17 {main}
ERROR - 2024-09-21 18:57:07 --> ErrorException: pg_query(): Query failed: ERROR:  ya existe la columna «precio_3» en la relación «producto» in C:\xampp\htdocs\dfpyme\system\Database\Postgre\Connection.php:135
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135)
#1 C:\xampp\htdocs\dfpyme\system\Database\Postgre\Connection.php(135): pg_query(Resource id #177, 'ALTER TABLE "pr...')
#2 C:\xampp\htdocs\dfpyme\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('ALTER TABLE "pr...')
#3 C:\xampp\htdocs\dfpyme\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('ALTER TABLE "pr...')
#4 C:\xampp\htdocs\dfpyme\system\Database\Forge.php(722): CodeIgniter\Database\BaseConnection->query('ALTER TABLE "pr...')
#5 C:\xampp\htdocs\dfpyme\app\Database\Migrations\2024-09-21-025053_AddPrecio3ToProductos.php(13): CodeIgniter\Database\Forge->addColumn('producto', Array)
#6 C:\xampp\htdocs\dfpyme\system\Database\MigrationRunner.php(863): App\Database\Migrations\AddPrecio3ToProductos->up()
#7 C:\xampp\htdocs\dfpyme\system\Database\MigrationRunner.php(186): CodeIgniter\Database\MigrationRunner->migrate('up', Object(stdClass))
#8 C:\xampp\htdocs\dfpyme\system\Commands\Database\Migrate.php(84): CodeIgniter\Database\MigrationRunner->latest(NULL)
#9 C:\xampp\htdocs\dfpyme\system\CLI\Commands.php(63): CodeIgniter\Commands\Database\Migrate->run(Array)
#10 C:\xampp\htdocs\dfpyme\system\CLI\CommandRunner.php(70): CodeIgniter\CLI\Commands->run('migrate', Array)
#11 C:\xampp\htdocs\dfpyme\system\CLI\CommandRunner.php(56): CodeIgniter\CLI\CommandRunner->index(Array)
#12 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(830): CodeIgniter\CLI\CommandRunner->_remap('index', 'migrate')
#13 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(CodeIgniter\CLI\CommandRunner))
#14 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#15 C:\xampp\htdocs\dfpyme\system\CLI\Console.php(48): CodeIgniter\CodeIgniter->run()
#16 C:\xampp\htdocs\dfpyme\spark(63): CodeIgniter\CLI\Console->run()
#17 {main}
ERROR - 2024-09-21 18:58:13 --> ErrorException: pg_query(): Query failed: ERROR:  llave duplicada viola restricción de unicidad «pk_migrations»
DETAIL:  Ya existe la llave (id)=(1). in C:\xampp\htdocs\dfpyme\system\Database\Postgre\Connection.php:135
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135)
#1 C:\xampp\htdocs\dfpyme\system\Database\Postgre\Connection.php(135): pg_query(Resource id #177, 'INSERT INTO "mi...')
#2 C:\xampp\htdocs\dfpyme\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('INSERT INTO "mi...')
#3 C:\xampp\htdocs\dfpyme\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO "mi...')
#4 C:\xampp\htdocs\dfpyme\system\Database\BaseBuilder.php(1771): CodeIgniter\Database\BaseConnection->query('INSERT INTO "mi...', Array, false)
#5 C:\xampp\htdocs\dfpyme\system\Database\MigrationRunner.php(595): CodeIgniter\Database\BaseBuilder->insert(Array)
#6 C:\xampp\htdocs\dfpyme\system\Database\MigrationRunner.php(193): CodeIgniter\Database\MigrationRunner->addHistory(Object(stdClass), 2)
#7 C:\xampp\htdocs\dfpyme\system\Commands\Database\Migrate.php(84): CodeIgniter\Database\MigrationRunner->latest(NULL)
#8 C:\xampp\htdocs\dfpyme\system\CLI\Commands.php(63): CodeIgniter\Commands\Database\Migrate->run(Array)
#9 C:\xampp\htdocs\dfpyme\system\CLI\CommandRunner.php(70): CodeIgniter\CLI\Commands->run('migrate', Array)
#10 C:\xampp\htdocs\dfpyme\system\CLI\CommandRunner.php(56): CodeIgniter\CLI\CommandRunner->index(Array)
#11 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(830): CodeIgniter\CLI\CommandRunner->_remap('index', 'migrate')
#12 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(CodeIgniter\CLI\CommandRunner))
#13 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#14 C:\xampp\htdocs\dfpyme\system\CLI\Console.php(48): CodeIgniter\CodeIgniter->run()
#15 C:\xampp\htdocs\dfpyme\spark(63): CodeIgniter\CLI\Console->run()
#16 {main}
