CRITICAL - 2022-05-09 08:38:20 --> Trying to access array offset on value of type null
#0 C:\xampp\htdocs\web\app\Controllers\producto\productoController.php(477): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Trying to acces...', 'C:\\xampp\\htdocs...', 477)
#1 C:\xampp\htdocs\web\system\CodeIgniter.php(832): App\Controllers\producto\productoController->cargar_producto_al_pedido()
#2 C:\xampp\htdocs\web\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\producto\productoController))
#3 C:\xampp\htdocs\web\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\web\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-05-09 08:38:20 --> Trying to access array offset on value of type null
#0 C:\xampp\htdocs\web\app\Controllers\producto\productoController.php(477): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Trying to acces...', 'C:\\xampp\\htdocs...', 477)
#1 C:\xampp\htdocs\web\system\CodeIgniter.php(832): App\Controllers\producto\productoController->cargar_producto_al_pedido()
#2 C:\xampp\htdocs\web\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\producto\productoController))
#3 C:\xampp\htdocs\web\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\web\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-05-09 08:38:20 --> Trying to access array offset on value of type null
#0 C:\xampp\htdocs\web\app\Controllers\producto\productoController.php(477): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Trying to acces...', 'C:\\xampp\\htdocs...', 477)
#1 C:\xampp\htdocs\web\system\CodeIgniter.php(832): App\Controllers\producto\productoController->cargar_producto_al_pedido()
#2 C:\xampp\htdocs\web\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\producto\productoController))
#3 C:\xampp\htdocs\web\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\web\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-05-09 08:38:20 --> Trying to access array offset on value of type null
#0 C:\xampp\htdocs\web\app\Controllers\producto\productoController.php(477): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Trying to acces...', 'C:\\xampp\\htdocs...', 477)
#1 C:\xampp\htdocs\web\system\CodeIgniter.php(832): App\Controllers\producto\productoController->cargar_producto_al_pedido()
#2 C:\xampp\htdocs\web\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\producto\productoController))
#3 C:\xampp\htdocs\web\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\web\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-05-09 08:38:20 --> Trying to access array offset on value of type null
#0 C:\xampp\htdocs\web\app\Controllers\producto\productoController.php(477): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Trying to acces...', 'C:\\xampp\\htdocs...', 477)
#1 C:\xampp\htdocs\web\system\CodeIgniter.php(832): App\Controllers\producto\productoController->cargar_producto_al_pedido()
#2 C:\xampp\htdocs\web\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\producto\productoController))
#3 C:\xampp\htdocs\web\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\web\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-05-09 08:38:21 --> Trying to access array offset on value of type null
#0 C:\xampp\htdocs\web\app\Controllers\producto\productoController.php(477): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Trying to acces...', 'C:\\xampp\\htdocs...', 477)
#1 C:\xampp\htdocs\web\system\CodeIgniter.php(832): App\Controllers\producto\productoController->cargar_producto_al_pedido()
#2 C:\xampp\htdocs\web\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\producto\productoController))
#3 C:\xampp\htdocs\web\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\web\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-05-09 08:38:21 --> Trying to access array offset on value of type null
#0 C:\xampp\htdocs\web\app\Controllers\producto\productoController.php(477): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Trying to acces...', 'C:\\xampp\\htdocs...', 477)
#1 C:\xampp\htdocs\web\system\CodeIgniter.php(832): App\Controllers\producto\productoController->cargar_producto_al_pedido()
#2 C:\xampp\htdocs\web\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\producto\productoController))
#3 C:\xampp\htdocs\web\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\web\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-05-09 08:38:21 --> Trying to access array offset on value of type null
#0 C:\xampp\htdocs\web\app\Controllers\producto\productoController.php(477): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Trying to acces...', 'C:\\xampp\\htdocs...', 477)
#1 C:\xampp\htdocs\web\system\CodeIgniter.php(832): App\Controllers\producto\productoController->cargar_producto_al_pedido()
#2 C:\xampp\htdocs\web\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\producto\productoController))
#3 C:\xampp\htdocs\web\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\web\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-05-09 08:38:21 --> Trying to access array offset on value of type null
#0 C:\xampp\htdocs\web\app\Controllers\producto\productoController.php(477): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Trying to acces...', 'C:\\xampp\\htdocs...', 477)
#1 C:\xampp\htdocs\web\system\CodeIgniter.php(832): App\Controllers\producto\productoController->cargar_producto_al_pedido()
#2 C:\xampp\htdocs\web\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\producto\productoController))
#3 C:\xampp\htdocs\web\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\web\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-05-09 08:38:21 --> Trying to access array offset on value of type null
#0 C:\xampp\htdocs\web\app\Controllers\producto\productoController.php(477): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Trying to acces...', 'C:\\xampp\\htdocs...', 477)
#1 C:\xampp\htdocs\web\system\CodeIgniter.php(832): App\Controllers\producto\productoController->cargar_producto_al_pedido()
#2 C:\xampp\htdocs\web\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\producto\productoController))
#3 C:\xampp\htdocs\web\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\web\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-05-09 08:38:22 --> Trying to access array offset on value of type null
#0 C:\xampp\htdocs\web\app\Controllers\producto\productoController.php(477): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Trying to acces...', 'C:\\xampp\\htdocs...', 477)
#1 C:\xampp\htdocs\web\system\CodeIgniter.php(832): App\Controllers\producto\productoController->cargar_producto_al_pedido()
#2 C:\xampp\htdocs\web\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\producto\productoController))
#3 C:\xampp\htdocs\web\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\web\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-05-09 08:38:22 --> Trying to access array offset on value of type null
#0 C:\xampp\htdocs\web\app\Controllers\producto\productoController.php(477): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Trying to acces...', 'C:\\xampp\\htdocs...', 477)
#1 C:\xampp\htdocs\web\system\CodeIgniter.php(832): App\Controllers\producto\productoController->cargar_producto_al_pedido()
#2 C:\xampp\htdocs\web\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\producto\productoController))
#3 C:\xampp\htdocs\web\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\web\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-05-09 08:40:44 --> Trying to access array offset on value of type null
#0 C:\xampp\htdocs\web\app\Controllers\producto\productoController.php(477): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Trying to acces...', 'C:\\xampp\\htdocs...', 477)
#1 C:\xampp\htdocs\web\system\CodeIgniter.php(832): App\Controllers\producto\productoController->cargar_producto_al_pedido()
#2 C:\xampp\htdocs\web\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\producto\productoController))
#3 C:\xampp\htdocs\web\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\web\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-05-09 08:40:46 --> Trying to access array offset on value of type null
#0 C:\xampp\htdocs\web\app\Controllers\producto\productoController.php(477): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Trying to acces...', 'C:\\xampp\\htdocs...', 477)
#1 C:\xampp\htdocs\web\system\CodeIgniter.php(832): App\Controllers\producto\productoController->cargar_producto_al_pedido()
#2 C:\xampp\htdocs\web\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\producto\productoController))
#3 C:\xampp\htdocs\web\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\web\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-05-09 08:40:46 --> Trying to access array offset on value of type null
#0 C:\xampp\htdocs\web\app\Controllers\producto\productoController.php(477): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Trying to acces...', 'C:\\xampp\\htdocs...', 477)
#1 C:\xampp\htdocs\web\system\CodeIgniter.php(832): App\Controllers\producto\productoController->cargar_producto_al_pedido()
#2 C:\xampp\htdocs\web\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\producto\productoController))
#3 C:\xampp\htdocs\web\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\web\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-05-09 08:40:48 --> Trying to access array offset on value of type null
#0 C:\xampp\htdocs\web\app\Controllers\producto\productoController.php(477): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Trying to acces...', 'C:\\xampp\\htdocs...', 477)
#1 C:\xampp\htdocs\web\system\CodeIgniter.php(832): App\Controllers\producto\productoController->cargar_producto_al_pedido()
#2 C:\xampp\htdocs\web\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\producto\productoController))
#3 C:\xampp\htdocs\web\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\web\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-05-09 08:40:48 --> Trying to access array offset on value of type null
#0 C:\xampp\htdocs\web\app\Controllers\producto\productoController.php(477): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Trying to acces...', 'C:\\xampp\\htdocs...', 477)
#1 C:\xampp\htdocs\web\system\CodeIgniter.php(832): App\Controllers\producto\productoController->cargar_producto_al_pedido()
#2 C:\xampp\htdocs\web\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\producto\productoController))
#3 C:\xampp\htdocs\web\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\web\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-05-09 08:40:48 --> Trying to access array offset on value of type null
#0 C:\xampp\htdocs\web\app\Controllers\producto\productoController.php(477): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Trying to acces...', 'C:\\xampp\\htdocs...', 477)
#1 C:\xampp\htdocs\web\system\CodeIgniter.php(832): App\Controllers\producto\productoController->cargar_producto_al_pedido()
#2 C:\xampp\htdocs\web\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\producto\productoController))
#3 C:\xampp\htdocs\web\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\web\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-05-09 08:40:48 --> Trying to access array offset on value of type null
#0 C:\xampp\htdocs\web\app\Controllers\producto\productoController.php(477): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Trying to acces...', 'C:\\xampp\\htdocs...', 477)
#1 C:\xampp\htdocs\web\system\CodeIgniter.php(832): App\Controllers\producto\productoController->cargar_producto_al_pedido()
#2 C:\xampp\htdocs\web\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\producto\productoController))
#3 C:\xampp\htdocs\web\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\web\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-05-09 11:53:39 --> Undefined array key "valorventaproducto"
#0 C:\xampp\htdocs\web\app\Controllers\factura_pos\facturaDirectaController.php(449): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array...', 'C:\\xampp\\htdocs...', 449)
#1 C:\xampp\htdocs\web\app\Controllers\factura_pos\facturaDirectaController.php(44): App\Controllers\factura_pos\facturaDirectaController->facturacion_con_impuestos('10000', '30000', '27800', '22222222', '8', '1', '1000030000')
#2 C:\xampp\htdocs\web\system\CodeIgniter.php(832): App\Controllers\factura_pos\facturaDirectaController->facturacion()
#3 C:\xampp\htdocs\web\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\factura_pos\facturaDirectaController))
#4 C:\xampp\htdocs\web\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\web\index.php(37): CodeIgniter\CodeIgniter->run()
#6 {main}
ERROR - 2022-05-09 13:00:30 --> ErrorException: pg_query(): Query failed: ERROR:  la sintaxis de entrada no es válida para tipo date: «»
LINE 9:         fecha_factura_venta BETWEEN '' AND '';
                                            ^ in C:\xampp\htdocs\web\system\Database\Postgre\Connection.php:135
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135)
#1 C:\xampp\htdocs\web\system\Database\Postgre\Connection.php(135): pg_query(Resource id #131, '\r\n        SELEC...')
#2 C:\xampp\htdocs\web\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('\r\n        SELEC...')
#3 C:\xampp\htdocs\web\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('\r\n        SELEC...')
#4 C:\xampp\htdocs\web\app\Models\facturaVentaModel.php(24): CodeIgniter\Database\BaseConnection->query('\r\n        SELEC...')
#5 C:\xampp\htdocs\web\app\Controllers\consultas_y_reportes\duplicadoFacturaController.php(24): App\Models\facturaVentaModel->facturas_por_rango_de_fechas('', '')
#6 C:\xampp\htdocs\web\system\CodeIgniter.php(832): App\Controllers\consultas_y_reportes\duplicadoFacturaController->facturas_por_rango_de_fechas()
#7 C:\xampp\htdocs\web\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\consultas_y_reportes\duplicadoFacturaController))
#8 C:\xampp\htdocs\web\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\web\index.php(37): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2022-05-09 13:00:30 --> pg_query(): Query failed: ERROR:  la sintaxis de entrada no es válida para tipo date: «»
LINE 9:         fecha_factura_venta BETWEEN '' AND '';
                                            ^
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135)
#1 C:\xampp\htdocs\web\system\Database\Postgre\Connection.php(135): pg_query(Resource id #131, '\r\n        SELEC...')
#2 C:\xampp\htdocs\web\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('\r\n        SELEC...')
#3 C:\xampp\htdocs\web\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('\r\n        SELEC...')
#4 C:\xampp\htdocs\web\app\Models\facturaVentaModel.php(24): CodeIgniter\Database\BaseConnection->query('\r\n        SELEC...')
#5 C:\xampp\htdocs\web\app\Controllers\consultas_y_reportes\duplicadoFacturaController.php(24): App\Models\facturaVentaModel->facturas_por_rango_de_fechas('', '')
#6 C:\xampp\htdocs\web\system\CodeIgniter.php(832): App\Controllers\consultas_y_reportes\duplicadoFacturaController->facturas_por_rango_de_fechas()
#7 C:\xampp\htdocs\web\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\consultas_y_reportes\duplicadoFacturaController))
#8 C:\xampp\htdocs\web\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\web\index.php(37): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2022-05-09 13:00:30 --> Uncaught CodeIgniter\Format\Exceptions\FormatException: Failed to parse json string, error: "Type is not supported". in C:\xampp\htdocs\web\system\Format\JSONFormatter.php:41
Stack trace:
#0 C:\xampp\htdocs\web\system\Format\JSONFormatter.php(41): CodeIgniter\Format\Exceptions\FormatException::forInvalidJSON('Type is not sup...')
#1 C:\xampp\htdocs\web\system\API\ResponseTrait.php(341): CodeIgniter\Format\JSONFormatter->format(Array)
#2 C:\xampp\htdocs\web\system\API\ResponseTrait.php(99): CodeIgniter\Debug\Exceptions->format(Array)
#3 C:\xampp\htdocs\web\system\Debug\Exceptions.php(115): CodeIgniter\Debug\Exceptions->respond(Array, 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(ErrorException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
ERROR - 2022-05-09 13:00:32 --> ErrorException: pg_query(): Query failed: ERROR:  la sintaxis de entrada no es válida para tipo date: «»
LINE 9:         fecha_factura_venta BETWEEN '' AND '';
                                            ^ in C:\xampp\htdocs\web\system\Database\Postgre\Connection.php:135
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135)
#1 C:\xampp\htdocs\web\system\Database\Postgre\Connection.php(135): pg_query(Resource id #131, '\r\n        SELEC...')
#2 C:\xampp\htdocs\web\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('\r\n        SELEC...')
#3 C:\xampp\htdocs\web\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('\r\n        SELEC...')
#4 C:\xampp\htdocs\web\app\Models\facturaVentaModel.php(24): CodeIgniter\Database\BaseConnection->query('\r\n        SELEC...')
#5 C:\xampp\htdocs\web\app\Controllers\consultas_y_reportes\duplicadoFacturaController.php(24): App\Models\facturaVentaModel->facturas_por_rango_de_fechas('', '')
#6 C:\xampp\htdocs\web\system\CodeIgniter.php(832): App\Controllers\consultas_y_reportes\duplicadoFacturaController->facturas_por_rango_de_fechas()
#7 C:\xampp\htdocs\web\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\consultas_y_reportes\duplicadoFacturaController))
#8 C:\xampp\htdocs\web\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\web\index.php(37): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2022-05-09 13:00:32 --> pg_query(): Query failed: ERROR:  la sintaxis de entrada no es válida para tipo date: «»
LINE 9:         fecha_factura_venta BETWEEN '' AND '';
                                            ^
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135)
#1 C:\xampp\htdocs\web\system\Database\Postgre\Connection.php(135): pg_query(Resource id #131, '\r\n        SELEC...')
#2 C:\xampp\htdocs\web\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('\r\n        SELEC...')
#3 C:\xampp\htdocs\web\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('\r\n        SELEC...')
#4 C:\xampp\htdocs\web\app\Models\facturaVentaModel.php(24): CodeIgniter\Database\BaseConnection->query('\r\n        SELEC...')
#5 C:\xampp\htdocs\web\app\Controllers\consultas_y_reportes\duplicadoFacturaController.php(24): App\Models\facturaVentaModel->facturas_por_rango_de_fechas('', '')
#6 C:\xampp\htdocs\web\system\CodeIgniter.php(832): App\Controllers\consultas_y_reportes\duplicadoFacturaController->facturas_por_rango_de_fechas()
#7 C:\xampp\htdocs\web\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\consultas_y_reportes\duplicadoFacturaController))
#8 C:\xampp\htdocs\web\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\web\index.php(37): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2022-05-09 13:00:32 --> Uncaught CodeIgniter\Format\Exceptions\FormatException: Failed to parse json string, error: "Type is not supported". in C:\xampp\htdocs\web\system\Format\JSONFormatter.php:41
Stack trace:
#0 C:\xampp\htdocs\web\system\Format\JSONFormatter.php(41): CodeIgniter\Format\Exceptions\FormatException::forInvalidJSON('Type is not sup...')
#1 C:\xampp\htdocs\web\system\API\ResponseTrait.php(341): CodeIgniter\Format\JSONFormatter->format(Array)
#2 C:\xampp\htdocs\web\system\API\ResponseTrait.php(99): CodeIgniter\Debug\Exceptions->format(Array)
#3 C:\xampp\htdocs\web\system\Debug\Exceptions.php(115): CodeIgniter\Debug\Exceptions->respond(Array, 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(ErrorException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2022-05-09 14:06:59 --> Undefined array key "sum"
#0 C:\xampp\htdocs\web\app\Controllers\consultas_y_reportes\duplicadoFacturaController.php(26): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array...', 'C:\\xampp\\htdocs...', 26)
#1 C:\xampp\htdocs\web\system\CodeIgniter.php(832): App\Controllers\consultas_y_reportes\duplicadoFacturaController->facturas_por_rango_de_fechas()
#2 C:\xampp\htdocs\web\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\consultas_y_reportes\duplicadoFacturaController))
#3 C:\xampp\htdocs\web\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\web\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
ERROR - 2022-05-09 16:04:27 --> Error connecting to the database: pg_connect(): Unable to connect to PostgreSQL server: FATAL:  el sistema de base de datos est� en modo de recuperaci�n
CRITICAL - 2022-05-09 16:04:27 --> Unable to connect to the database.
Main connection [Postgre]: pg_connect(): Unable to connect to PostgreSQL server: FATAL:  el sistema de base de datos est� en modo de recuperaci�n
#0 C:\xampp\htdocs\web\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\web\app\Models\pedidoModel.php(22): CodeIgniter\Database\BaseConnection->query('\r\n        SELEC...')
#2 C:\xampp\htdocs\web\app\Controllers\pedido\pedidoController.php(20): App\Models\pedidoModel->todosLospedidos()
#3 C:\xampp\htdocs\web\system\CodeIgniter.php(832): App\Controllers\pedido\pedidoController->pedidos_para_facturacion()
#4 C:\xampp\htdocs\web\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\pedido\pedidoController))
#5 C:\xampp\htdocs\web\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\web\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
ERROR - 2022-05-09 16:04:28 --> Error connecting to the database: pg_connect(): Unable to connect to PostgreSQL server: FATAL:  el sistema de base de datos est� en modo de recuperaci�n
CRITICAL - 2022-05-09 16:04:28 --> Unable to connect to the database.
Main connection [Postgre]: pg_connect(): Unable to connect to PostgreSQL server: FATAL:  el sistema de base de datos est� en modo de recuperaci�n
#0 C:\xampp\htdocs\web\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\web\app\Models\pedidoModel.php(22): CodeIgniter\Database\BaseConnection->query('\r\n        SELEC...')
#2 C:\xampp\htdocs\web\app\Controllers\pedido\pedidoController.php(20): App\Models\pedidoModel->todosLospedidos()
#3 C:\xampp\htdocs\web\system\CodeIgniter.php(832): App\Controllers\pedido\pedidoController->pedidos_para_facturacion()
#4 C:\xampp\htdocs\web\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\pedido\pedidoController))
#5 C:\xampp\htdocs\web\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\web\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
ERROR - 2022-05-09 16:04:29 --> Error connecting to the database: pg_connect(): Unable to connect to PostgreSQL server: FATAL:  el sistema de base de datos est� en modo de recuperaci�n
CRITICAL - 2022-05-09 16:04:29 --> Unable to connect to the database.
Main connection [Postgre]: pg_connect(): Unable to connect to PostgreSQL server: FATAL:  el sistema de base de datos est� en modo de recuperaci�n
#0 C:\xampp\htdocs\web\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\web\app\Models\pedidoModel.php(22): CodeIgniter\Database\BaseConnection->query('\r\n        SELEC...')
#2 C:\xampp\htdocs\web\app\Controllers\pedido\pedidoController.php(20): App\Models\pedidoModel->todosLospedidos()
#3 C:\xampp\htdocs\web\system\CodeIgniter.php(832): App\Controllers\pedido\pedidoController->pedidos_para_facturacion()
#4 C:\xampp\htdocs\web\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\pedido\pedidoController))
#5 C:\xampp\htdocs\web\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\web\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
ERROR - 2022-05-09 16:04:30 --> Error connecting to the database: pg_connect(): Unable to connect to PostgreSQL server: FATAL:  el sistema de base de datos est� en modo de recuperaci�n
CRITICAL - 2022-05-09 16:04:30 --> Unable to connect to the database.
Main connection [Postgre]: pg_connect(): Unable to connect to PostgreSQL server: FATAL:  el sistema de base de datos est� en modo de recuperaci�n
#0 C:\xampp\htdocs\web\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\web\app\Models\pedidoModel.php(22): CodeIgniter\Database\BaseConnection->query('\r\n        SELEC...')
#2 C:\xampp\htdocs\web\app\Controllers\pedido\pedidoController.php(20): App\Models\pedidoModel->todosLospedidos()
#3 C:\xampp\htdocs\web\system\CodeIgniter.php(832): App\Controllers\pedido\pedidoController->pedidos_para_facturacion()
#4 C:\xampp\htdocs\web\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\pedido\pedidoController))
#5 C:\xampp\htdocs\web\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\web\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-05-09 21:22:22 --> Undefined array key "numerofactura_venta"
#0 C:\xampp\htdocs\web\app\Views\duplicado_de_factura\facturas_por_rango_de_fecha.php(14): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array...', 'C:\\xampp\\htdocs...', 14)
#1 C:\xampp\htdocs\web\system\View\View.php(210): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\web\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\xampp\htdocs\web\system\Common.php(1089): CodeIgniter\View\View->render('duplicado_de_fa...', Array, true)
#4 C:\xampp\htdocs\web\app\Controllers\consultas_y_reportes\duplicadoFacturaController.php(38): view('duplicado_de_fa...', Array)
#5 C:\xampp\htdocs\web\system\CodeIgniter.php(832): App\Controllers\consultas_y_reportes\duplicadoFacturaController->facturas_por_rango_de_fechas()
#6 C:\xampp\htdocs\web\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\consultas_y_reportes\duplicadoFacturaController))
#7 C:\xampp\htdocs\web\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\web\index.php(37): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2022-05-09 21:23:05 --> Undefined array key 0
#0 C:\xampp\htdocs\web\app\Views\duplicado_de_factura\facturas_por_rango_de_fecha.php(14): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array...', 'C:\\xampp\\htdocs...', 14)
#1 C:\xampp\htdocs\web\system\View\View.php(210): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\web\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\xampp\htdocs\web\system\Common.php(1089): CodeIgniter\View\View->render('duplicado_de_fa...', Array, true)
#4 C:\xampp\htdocs\web\app\Controllers\consultas_y_reportes\duplicadoFacturaController.php(38): view('duplicado_de_fa...', Array)
#5 C:\xampp\htdocs\web\system\CodeIgniter.php(832): App\Controllers\consultas_y_reportes\duplicadoFacturaController->facturas_por_rango_de_fechas()
#6 C:\xampp\htdocs\web\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\consultas_y_reportes\duplicadoFacturaController))
#7 C:\xampp\htdocs\web\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\web\index.php(37): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2022-05-09 21:23:22 --> Undefined array key "numerofactura_venta"
#0 C:\xampp\htdocs\web\app\Views\duplicado_de_factura\facturas_por_rango_de_fecha.php(14): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array...', 'C:\\xampp\\htdocs...', 14)
#1 C:\xampp\htdocs\web\system\View\View.php(210): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\web\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\xampp\htdocs\web\system\Common.php(1089): CodeIgniter\View\View->render('duplicado_de_fa...', Array, true)
#4 C:\xampp\htdocs\web\app\Controllers\consultas_y_reportes\duplicadoFacturaController.php(38): view('duplicado_de_fa...', Array)
#5 C:\xampp\htdocs\web\system\CodeIgniter.php(832): App\Controllers\consultas_y_reportes\duplicadoFacturaController->facturas_por_rango_de_fechas()
#6 C:\xampp\htdocs\web\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\consultas_y_reportes\duplicadoFacturaController))
#7 C:\xampp\htdocs\web\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\web\index.php(37): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2022-05-09 21:26:48 --> Undefined array key "nitcliente"
#0 C:\xampp\htdocs\web\app\Views\duplicado_de_factura\facturas_por_rango_de_fecha.php(15): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array...', 'C:\\xampp\\htdocs...', 15)
#1 C:\xampp\htdocs\web\system\View\View.php(210): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\web\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\xampp\htdocs\web\system\Common.php(1089): CodeIgniter\View\View->render('duplicado_de_fa...', Array, true)
#4 C:\xampp\htdocs\web\app\Controllers\consultas_y_reportes\duplicadoFacturaController.php(38): view('duplicado_de_fa...', Array)
#5 C:\xampp\htdocs\web\system\CodeIgniter.php(832): App\Controllers\consultas_y_reportes\duplicadoFacturaController->facturas_por_rango_de_fechas()
#6 C:\xampp\htdocs\web\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\consultas_y_reportes\duplicadoFacturaController))
#7 C:\xampp\htdocs\web\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\web\index.php(37): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2022-05-09 21:37:28 --> Call to undefined method App\Models\duplicadoFacturaModel::facturas_por_rango_de_fechas
#0 C:\xampp\htdocs\web\app\Controllers\consultas_y_reportes\duplicadoFacturaController.php(38): CodeIgniter\Model->__call('facturas_por_ra...', Array)
#1 C:\xampp\htdocs\web\system\CodeIgniter.php(832): App\Controllers\consultas_y_reportes\duplicadoFacturaController->facturas_por_rango_de_fechas()
#2 C:\xampp\htdocs\web\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\consultas_y_reportes\duplicadoFacturaController))
#3 C:\xampp\htdocs\web\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\web\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
ERROR - 2022-05-09 21:38:53 --> ErrorException: pg_query(): Query failed: ERROR:  el operador no existe: date &gt;= integer
LINE 4:         WHERE fecha_factura BETWEEN 2022-05-09 and 2022-05-0...
                                    ^
HINT:  Ningún operador coincide con el nombre y el tipo de los argumentos. Puede ser necesario agregar conversiones explícitas de tipos. in C:\xampp\htdocs\web\system\Database\Postgre\Connection.php:135
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135)
#1 C:\xampp\htdocs\web\system\Database\Postgre\Connection.php(135): pg_query(Resource id #131, '\r\n        DELET...')
#2 C:\xampp\htdocs\web\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('\r\n        DELET...')
#3 C:\xampp\htdocs\web\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('\r\n        DELET...')
#4 C:\xampp\htdocs\web\app\Models\duplicadoFacturaModel.php(20): CodeIgniter\Database\BaseConnection->query('\r\n        DELET...')
#5 C:\xampp\htdocs\web\app\Controllers\consultas_y_reportes\duplicadoFacturaController.php(38): App\Models\duplicadoFacturaModel->borrar_tabla_duplicado_factura('2022-05-09', '2022-05-09')
#6 C:\xampp\htdocs\web\system\CodeIgniter.php(832): App\Controllers\consultas_y_reportes\duplicadoFacturaController->facturas_por_rango_de_fechas()
#7 C:\xampp\htdocs\web\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\consultas_y_reportes\duplicadoFacturaController))
#8 C:\xampp\htdocs\web\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\web\index.php(37): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2022-05-09 21:38:53 --> pg_query(): Query failed: ERROR:  el operador no existe: date &gt;= integer
LINE 4:         WHERE fecha_factura BETWEEN 2022-05-09 and 2022-05-0...
                                    ^
HINT:  Ningún operador coincide con el nombre y el tipo de los argumentos. Puede ser necesario agregar conversiones explícitas de tipos.
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135)
#1 C:\xampp\htdocs\web\system\Database\Postgre\Connection.php(135): pg_query(Resource id #131, '\r\n        DELET...')
#2 C:\xampp\htdocs\web\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('\r\n        DELET...')
#3 C:\xampp\htdocs\web\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('\r\n        DELET...')
#4 C:\xampp\htdocs\web\app\Models\duplicadoFacturaModel.php(20): CodeIgniter\Database\BaseConnection->query('\r\n        DELET...')
#5 C:\xampp\htdocs\web\app\Controllers\consultas_y_reportes\duplicadoFacturaController.php(38): App\Models\duplicadoFacturaModel->borrar_tabla_duplicado_factura('2022-05-09', '2022-05-09')
#6 C:\xampp\htdocs\web\system\CodeIgniter.php(832): App\Controllers\consultas_y_reportes\duplicadoFacturaController->facturas_por_rango_de_fechas()
#7 C:\xampp\htdocs\web\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\consultas_y_reportes\duplicadoFacturaController))
#8 C:\xampp\htdocs\web\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\web\index.php(37): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2022-05-09 21:38:53 --> Uncaught CodeIgniter\Format\Exceptions\FormatException: Failed to parse json string, error: "Type is not supported". in C:\xampp\htdocs\web\system\Format\JSONFormatter.php:41
Stack trace:
#0 C:\xampp\htdocs\web\system\Format\JSONFormatter.php(41): CodeIgniter\Format\Exceptions\FormatException::forInvalidJSON('Type is not sup...')
#1 C:\xampp\htdocs\web\system\API\ResponseTrait.php(341): CodeIgniter\Format\JSONFormatter->format(Array)
#2 C:\xampp\htdocs\web\system\API\ResponseTrait.php(99): CodeIgniter\Debug\Exceptions->format(Array)
#3 C:\xampp\htdocs\web\system\Debug\Exceptions.php(115): CodeIgniter\Debug\Exceptions->respond(Array, 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(ErrorException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
ERROR - 2022-05-09 21:39:43 --> ErrorException: pg_query(): Query failed: ERROR:  el operador no existe: date &gt;= integer
LINE 4:         WHERE fecha_factura BETWEEN 2022-05-09 and 2022-05-0...
                                    ^
HINT:  Ningún operador coincide con el nombre y el tipo de los argumentos. Puede ser necesario agregar conversiones explícitas de tipos. in C:\xampp\htdocs\web\system\Database\Postgre\Connection.php:135
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135)
#1 C:\xampp\htdocs\web\system\Database\Postgre\Connection.php(135): pg_query(Resource id #131, '\r\n        DELET...')
#2 C:\xampp\htdocs\web\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('\r\n        DELET...')
#3 C:\xampp\htdocs\web\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('\r\n        DELET...')
#4 C:\xampp\htdocs\web\app\Models\duplicadoFacturaModel.php(20): CodeIgniter\Database\BaseConnection->query('\r\n        DELET...')
#5 C:\xampp\htdocs\web\app\Controllers\consultas_y_reportes\duplicadoFacturaController.php(38): App\Models\duplicadoFacturaModel->borrar_tabla_duplicado_factura('2022-05-09', '2022-05-09')
#6 C:\xampp\htdocs\web\system\CodeIgniter.php(832): App\Controllers\consultas_y_reportes\duplicadoFacturaController->facturas_por_rango_de_fechas()
#7 C:\xampp\htdocs\web\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\consultas_y_reportes\duplicadoFacturaController))
#8 C:\xampp\htdocs\web\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\web\index.php(37): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2022-05-09 21:39:43 --> pg_query(): Query failed: ERROR:  el operador no existe: date &gt;= integer
LINE 4:         WHERE fecha_factura BETWEEN 2022-05-09 and 2022-05-0...
                                    ^
HINT:  Ningún operador coincide con el nombre y el tipo de los argumentos. Puede ser necesario agregar conversiones explícitas de tipos.
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135)
#1 C:\xampp\htdocs\web\system\Database\Postgre\Connection.php(135): pg_query(Resource id #131, '\r\n        DELET...')
#2 C:\xampp\htdocs\web\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('\r\n        DELET...')
#3 C:\xampp\htdocs\web\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('\r\n        DELET...')
#4 C:\xampp\htdocs\web\app\Models\duplicadoFacturaModel.php(20): CodeIgniter\Database\BaseConnection->query('\r\n        DELET...')
#5 C:\xampp\htdocs\web\app\Controllers\consultas_y_reportes\duplicadoFacturaController.php(38): App\Models\duplicadoFacturaModel->borrar_tabla_duplicado_factura('2022-05-09', '2022-05-09')
#6 C:\xampp\htdocs\web\system\CodeIgniter.php(832): App\Controllers\consultas_y_reportes\duplicadoFacturaController->facturas_por_rango_de_fechas()
#7 C:\xampp\htdocs\web\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\consultas_y_reportes\duplicadoFacturaController))
#8 C:\xampp\htdocs\web\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\web\index.php(37): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2022-05-09 21:39:43 --> Uncaught CodeIgniter\Format\Exceptions\FormatException: Failed to parse json string, error: "Type is not supported". in C:\xampp\htdocs\web\system\Format\JSONFormatter.php:41
Stack trace:
#0 C:\xampp\htdocs\web\system\Format\JSONFormatter.php(41): CodeIgniter\Format\Exceptions\FormatException::forInvalidJSON('Type is not sup...')
#1 C:\xampp\htdocs\web\system\API\ResponseTrait.php(341): CodeIgniter\Format\JSONFormatter->format(Array)
#2 C:\xampp\htdocs\web\system\API\ResponseTrait.php(99): CodeIgniter\Debug\Exceptions->format(Array)
#3 C:\xampp\htdocs\web\system\Debug\Exceptions.php(115): CodeIgniter\Debug\Exceptions->respond(Array, 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(ErrorException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
ERROR - 2022-05-09 21:43:40 --> ErrorException: pg_query(): Query failed: ERROR:  el operador no existe: date &gt;= integer
LINE 4:         WHERE fecha_factura BETWEEN 09-05-2022 and 09-05-202...
                                    ^
HINT:  Ningún operador coincide con el nombre y el tipo de los argumentos. Puede ser necesario agregar conversiones explícitas de tipos. in C:\xampp\htdocs\web\system\Database\Postgre\Connection.php:135
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135)
#1 C:\xampp\htdocs\web\system\Database\Postgre\Connection.php(135): pg_query(Resource id #131, '\r\n        DELET...')
#2 C:\xampp\htdocs\web\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('\r\n        DELET...')
#3 C:\xampp\htdocs\web\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('\r\n        DELET...')
#4 C:\xampp\htdocs\web\app\Models\duplicadoFacturaModel.php(20): CodeIgniter\Database\BaseConnection->query('\r\n        DELET...')
#5 C:\xampp\htdocs\web\app\Controllers\consultas_y_reportes\duplicadoFacturaController.php(41): App\Models\duplicadoFacturaModel->borrar_tabla_duplicado_factura('09-05-2022', '09-05-2022')
#6 C:\xampp\htdocs\web\system\CodeIgniter.php(832): App\Controllers\consultas_y_reportes\duplicadoFacturaController->facturas_por_rango_de_fechas()
#7 C:\xampp\htdocs\web\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\consultas_y_reportes\duplicadoFacturaController))
#8 C:\xampp\htdocs\web\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\web\index.php(37): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2022-05-09 21:43:40 --> pg_query(): Query failed: ERROR:  el operador no existe: date &gt;= integer
LINE 4:         WHERE fecha_factura BETWEEN 09-05-2022 and 09-05-202...
                                    ^
HINT:  Ningún operador coincide con el nombre y el tipo de los argumentos. Puede ser necesario agregar conversiones explícitas de tipos.
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135)
#1 C:\xampp\htdocs\web\system\Database\Postgre\Connection.php(135): pg_query(Resource id #131, '\r\n        DELET...')
#2 C:\xampp\htdocs\web\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('\r\n        DELET...')
#3 C:\xampp\htdocs\web\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('\r\n        DELET...')
#4 C:\xampp\htdocs\web\app\Models\duplicadoFacturaModel.php(20): CodeIgniter\Database\BaseConnection->query('\r\n        DELET...')
#5 C:\xampp\htdocs\web\app\Controllers\consultas_y_reportes\duplicadoFacturaController.php(41): App\Models\duplicadoFacturaModel->borrar_tabla_duplicado_factura('09-05-2022', '09-05-2022')
#6 C:\xampp\htdocs\web\system\CodeIgniter.php(832): App\Controllers\consultas_y_reportes\duplicadoFacturaController->facturas_por_rango_de_fechas()
#7 C:\xampp\htdocs\web\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\consultas_y_reportes\duplicadoFacturaController))
#8 C:\xampp\htdocs\web\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\web\index.php(37): CodeIgniter\CodeIgniter->run()
#10 {main}
ERROR - 2022-05-09 21:51:55 --> ErrorException: pg_query(): Query failed: ERROR:  el operador no existe: character varying &gt;= integer
LINE 4:         WHERE fecha_factura BETWEEN 09-05-2022 and 09-05-202...
                                    ^
HINT:  Ningún operador coincide con el nombre y el tipo de los argumentos. Puede ser necesario agregar conversiones explícitas de tipos. in C:\xampp\htdocs\web\system\Database\Postgre\Connection.php:135
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135)
#1 C:\xampp\htdocs\web\system\Database\Postgre\Connection.php(135): pg_query(Resource id #132, '\r\n        DELET...')
#2 C:\xampp\htdocs\web\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('\r\n        DELET...')
#3 C:\xampp\htdocs\web\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('\r\n        DELET...')
#4 C:\xampp\htdocs\web\app\Models\duplicadoFacturaModel.php(20): CodeIgniter\Database\BaseConnection->query('\r\n        DELET...')
#5 C:\xampp\htdocs\web\app\Controllers\consultas_y_reportes\duplicadoFacturaController.php(41): App\Models\duplicadoFacturaModel->borrar_tabla_duplicado_factura('09-05-2022', '09-05-2022')
#6 C:\xampp\htdocs\web\system\CodeIgniter.php(832): App\Controllers\consultas_y_reportes\duplicadoFacturaController->facturas_por_rango_de_fechas()
#7 C:\xampp\htdocs\web\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\consultas_y_reportes\duplicadoFacturaController))
#8 C:\xampp\htdocs\web\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\web\index.php(37): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2022-05-09 21:51:55 --> pg_query(): Query failed: ERROR:  el operador no existe: character varying &gt;= integer
LINE 4:         WHERE fecha_factura BETWEEN 09-05-2022 and 09-05-202...
                                    ^
HINT:  Ningún operador coincide con el nombre y el tipo de los argumentos. Puede ser necesario agregar conversiones explícitas de tipos.
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135)
#1 C:\xampp\htdocs\web\system\Database\Postgre\Connection.php(135): pg_query(Resource id #132, '\r\n        DELET...')
#2 C:\xampp\htdocs\web\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('\r\n        DELET...')
#3 C:\xampp\htdocs\web\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('\r\n        DELET...')
#4 C:\xampp\htdocs\web\app\Models\duplicadoFacturaModel.php(20): CodeIgniter\Database\BaseConnection->query('\r\n        DELET...')
#5 C:\xampp\htdocs\web\app\Controllers\consultas_y_reportes\duplicadoFacturaController.php(41): App\Models\duplicadoFacturaModel->borrar_tabla_duplicado_factura('09-05-2022', '09-05-2022')
#6 C:\xampp\htdocs\web\system\CodeIgniter.php(832): App\Controllers\consultas_y_reportes\duplicadoFacturaController->facturas_por_rango_de_fechas()
#7 C:\xampp\htdocs\web\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\consultas_y_reportes\duplicadoFacturaController))
#8 C:\xampp\htdocs\web\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\web\index.php(37): CodeIgniter\CodeIgniter->run()
#10 {main}
ERROR - 2022-05-09 21:54:38 --> ErrorException: pg_query(): Query failed: ERROR:  el operador no existe: character varying &gt;= integer
LINE 4:         WHERE fecha_factura BETWEEN 09-05-2022 and 09-05-202...
                                    ^
HINT:  Ningún operador coincide con el nombre y el tipo de los argumentos. Puede ser necesario agregar conversiones explícitas de tipos. in C:\xampp\htdocs\web\system\Database\Postgre\Connection.php:135
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135)
#1 C:\xampp\htdocs\web\system\Database\Postgre\Connection.php(135): pg_query(Resource id #131, '\r\n        DELET...')
#2 C:\xampp\htdocs\web\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('\r\n        DELET...')
#3 C:\xampp\htdocs\web\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('\r\n        DELET...')
#4 C:\xampp\htdocs\web\app\Models\duplicadoFacturaModel.php(20): CodeIgniter\Database\BaseConnection->query('\r\n        DELET...')
#5 C:\xampp\htdocs\web\app\Controllers\consultas_y_reportes\duplicadoFacturaController.php(41): App\Models\duplicadoFacturaModel->borrar_tabla_duplicado_factura('09-05-2022', '09-05-2022')
#6 C:\xampp\htdocs\web\system\CodeIgniter.php(832): App\Controllers\consultas_y_reportes\duplicadoFacturaController->facturas_por_rango_de_fechas()
#7 C:\xampp\htdocs\web\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\consultas_y_reportes\duplicadoFacturaController))
#8 C:\xampp\htdocs\web\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\web\index.php(37): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2022-05-09 21:54:38 --> pg_query(): Query failed: ERROR:  el operador no existe: character varying &gt;= integer
LINE 4:         WHERE fecha_factura BETWEEN 09-05-2022 and 09-05-202...
                                    ^
HINT:  Ningún operador coincide con el nombre y el tipo de los argumentos. Puede ser necesario agregar conversiones explícitas de tipos.
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135)
#1 C:\xampp\htdocs\web\system\Database\Postgre\Connection.php(135): pg_query(Resource id #131, '\r\n        DELET...')
#2 C:\xampp\htdocs\web\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('\r\n        DELET...')
#3 C:\xampp\htdocs\web\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('\r\n        DELET...')
#4 C:\xampp\htdocs\web\app\Models\duplicadoFacturaModel.php(20): CodeIgniter\Database\BaseConnection->query('\r\n        DELET...')
#5 C:\xampp\htdocs\web\app\Controllers\consultas_y_reportes\duplicadoFacturaController.php(41): App\Models\duplicadoFacturaModel->borrar_tabla_duplicado_factura('09-05-2022', '09-05-2022')
#6 C:\xampp\htdocs\web\system\CodeIgniter.php(832): App\Controllers\consultas_y_reportes\duplicadoFacturaController->facturas_por_rango_de_fechas()
#7 C:\xampp\htdocs\web\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\consultas_y_reportes\duplicadoFacturaController))
#8 C:\xampp\htdocs\web\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\web\index.php(37): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2022-05-09 22:05:37 --> Undefined array key "fecha_inicial"
#0 C:\xampp\htdocs\web\app\Controllers\consultas_y_reportes\duplicadoFacturaController.php(21): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array...', 'C:\\xampp\\htdocs...', 21)
#1 C:\xampp\htdocs\web\system\CodeIgniter.php(832): App\Controllers\consultas_y_reportes\duplicadoFacturaController->facturas_por_rango_de_fechas()
#2 C:\xampp\htdocs\web\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\consultas_y_reportes\duplicadoFacturaController))
#3 C:\xampp\htdocs\web\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\web\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
ERROR - 2022-05-09 22:07:09 --> ErrorException: pg_query(): Query failed: ERROR:  el operador no existe: character varying &gt;= integer
LINE 4:         WHERE fecha_factura BETWEEN 2022-05-09 and 2022-05-0...
                                    ^
HINT:  Ningún operador coincide con el nombre y el tipo de los argumentos. Puede ser necesario agregar conversiones explícitas de tipos. in C:\xampp\htdocs\web\system\Database\Postgre\Connection.php:135
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135)
#1 C:\xampp\htdocs\web\system\Database\Postgre\Connection.php(135): pg_query(Resource id #131, '\r\n        DELET...')
#2 C:\xampp\htdocs\web\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('\r\n        DELET...')
#3 C:\xampp\htdocs\web\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('\r\n        DELET...')
#4 C:\xampp\htdocs\web\app\Models\duplicadoFacturaModel.php(20): CodeIgniter\Database\BaseConnection->query('\r\n        DELET...')
#5 C:\xampp\htdocs\web\app\Controllers\consultas_y_reportes\duplicadoFacturaController.php(42): App\Models\duplicadoFacturaModel->borrar_tabla_duplicado_factura('2022-05-09', '2022-05-09')
#6 C:\xampp\htdocs\web\system\CodeIgniter.php(832): App\Controllers\consultas_y_reportes\duplicadoFacturaController->facturas_por_rango_de_fechas()
#7 C:\xampp\htdocs\web\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\consultas_y_reportes\duplicadoFacturaController))
#8 C:\xampp\htdocs\web\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\web\index.php(37): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2022-05-09 22:07:09 --> pg_query(): Query failed: ERROR:  el operador no existe: character varying &gt;= integer
LINE 4:         WHERE fecha_factura BETWEEN 2022-05-09 and 2022-05-0...
                                    ^
HINT:  Ningún operador coincide con el nombre y el tipo de los argumentos. Puede ser necesario agregar conversiones explícitas de tipos.
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135)
#1 C:\xampp\htdocs\web\system\Database\Postgre\Connection.php(135): pg_query(Resource id #131, '\r\n        DELET...')
#2 C:\xampp\htdocs\web\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('\r\n        DELET...')
#3 C:\xampp\htdocs\web\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('\r\n        DELET...')
#4 C:\xampp\htdocs\web\app\Models\duplicadoFacturaModel.php(20): CodeIgniter\Database\BaseConnection->query('\r\n        DELET...')
#5 C:\xampp\htdocs\web\app\Controllers\consultas_y_reportes\duplicadoFacturaController.php(42): App\Models\duplicadoFacturaModel->borrar_tabla_duplicado_factura('2022-05-09', '2022-05-09')
#6 C:\xampp\htdocs\web\system\CodeIgniter.php(832): App\Controllers\consultas_y_reportes\duplicadoFacturaController->facturas_por_rango_de_fechas()
#7 C:\xampp\htdocs\web\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\consultas_y_reportes\duplicadoFacturaController))
#8 C:\xampp\htdocs\web\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\web\index.php(37): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2022-05-09 22:07:09 --> Uncaught CodeIgniter\Format\Exceptions\FormatException: Failed to parse json string, error: "Type is not supported". in C:\xampp\htdocs\web\system\Format\JSONFormatter.php:41
Stack trace:
#0 C:\xampp\htdocs\web\system\Format\JSONFormatter.php(41): CodeIgniter\Format\Exceptions\FormatException::forInvalidJSON('Type is not sup...')
#1 C:\xampp\htdocs\web\system\API\ResponseTrait.php(341): CodeIgniter\Format\JSONFormatter->format(Array)
#2 C:\xampp\htdocs\web\system\API\ResponseTrait.php(99): CodeIgniter\Debug\Exceptions->format(Array)
#3 C:\xampp\htdocs\web\system\Debug\Exceptions.php(115): CodeIgniter\Debug\Exceptions->respond(Array, 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(ErrorException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
ERROR - 2022-05-09 22:25:35 --> ErrorException: pg_query(): Query failed: ERROR:  no existe la columna «numero_de_pedido»
LINE 2: WHERE &quot;numero_de_pedido&quot; = 8
              ^ in C:\xampp\htdocs\web\system\Database\Postgre\Connection.php:135
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135)
#1 C:\xampp\htdocs\web\system\Database\Postgre\Connection.php(135): pg_query(Resource id #131, 'DELETE FROM "du...')
#2 C:\xampp\htdocs\web\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('DELETE FROM "du...')
#3 C:\xampp\htdocs\web\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('DELETE FROM "du...')
#4 C:\xampp\htdocs\web\system\Database\BaseBuilder.php(2225): CodeIgniter\Database\BaseConnection->query('DELETE FROM "du...', Array, false)
#5 C:\xampp\htdocs\web\system\Database\Postgre\Builder.php(204): CodeIgniter\Database\BaseBuilder->delete('', NULL, true)
#6 C:\xampp\htdocs\web\system\Model.php(359): CodeIgniter\Database\Postgre\Builder->delete()
#7 C:\xampp\htdocs\web\system\BaseModel.php(963): CodeIgniter\Model->doDelete(NULL, false)
#8 C:\xampp\htdocs\web\app\Controllers\consultas_y_reportes\duplicadoFacturaController.php(43): CodeIgniter\BaseModel->delete()
#9 C:\xampp\htdocs\web\system\CodeIgniter.php(832): App\Controllers\consultas_y_reportes\duplicadoFacturaController->facturas_por_rango_de_fechas()
#10 C:\xampp\htdocs\web\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\consultas_y_reportes\duplicadoFacturaController))
#11 C:\xampp\htdocs\web\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\web\index.php(37): CodeIgniter\CodeIgniter->run()
#13 {main}
CRITICAL - 2022-05-09 22:25:35 --> pg_query(): Query failed: ERROR:  no existe la columna «numero_de_pedido»
LINE 2: WHERE &quot;numero_de_pedido&quot; = 8
              ^
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135)
#1 C:\xampp\htdocs\web\system\Database\Postgre\Connection.php(135): pg_query(Resource id #131, 'DELETE FROM "du...')
#2 C:\xampp\htdocs\web\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('DELETE FROM "du...')
#3 C:\xampp\htdocs\web\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('DELETE FROM "du...')
#4 C:\xampp\htdocs\web\system\Database\BaseBuilder.php(2225): CodeIgniter\Database\BaseConnection->query('DELETE FROM "du...', Array, false)
#5 C:\xampp\htdocs\web\system\Database\Postgre\Builder.php(204): CodeIgniter\Database\BaseBuilder->delete('', NULL, true)
#6 C:\xampp\htdocs\web\system\Model.php(359): CodeIgniter\Database\Postgre\Builder->delete()
#7 C:\xampp\htdocs\web\system\BaseModel.php(963): CodeIgniter\Model->doDelete(NULL, false)
#8 C:\xampp\htdocs\web\app\Controllers\consultas_y_reportes\duplicadoFacturaController.php(43): CodeIgniter\BaseModel->delete()
#9 C:\xampp\htdocs\web\system\CodeIgniter.php(832): App\Controllers\consultas_y_reportes\duplicadoFacturaController->facturas_por_rango_de_fechas()
#10 C:\xampp\htdocs\web\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\consultas_y_reportes\duplicadoFacturaController))
#11 C:\xampp\htdocs\web\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\web\index.php(37): CodeIgniter\CodeIgniter->run()
#13 {main}
CRITICAL - 2022-05-09 22:25:35 --> Uncaught CodeIgniter\Format\Exceptions\FormatException: Failed to parse json string, error: "Type is not supported". in C:\xampp\htdocs\web\system\Format\JSONFormatter.php:41
Stack trace:
#0 C:\xampp\htdocs\web\system\Format\JSONFormatter.php(41): CodeIgniter\Format\Exceptions\FormatException::forInvalidJSON('Type is not sup...')
#1 C:\xampp\htdocs\web\system\API\ResponseTrait.php(341): CodeIgniter\Format\JSONFormatter->format(Array)
#2 C:\xampp\htdocs\web\system\API\ResponseTrait.php(99): CodeIgniter\Debug\Exceptions->format(Array)
#3 C:\xampp\htdocs\web\system\Debug\Exceptions.php(115): CodeIgniter\Debug\Exceptions->respond(Array, 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(ErrorException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2022-05-09 22:34:16 --> Undefined array key "id_usuario"
#0 C:\xampp\htdocs\web\app\Controllers\consultas_y_reportes\duplicadoFacturaController.php(23): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array...', 'C:\\xampp\\htdocs...', 23)
#1 C:\xampp\htdocs\web\system\CodeIgniter.php(832): App\Controllers\consultas_y_reportes\duplicadoFacturaController->facturas_por_rango_de_fechas()
#2 C:\xampp\htdocs\web\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\consultas_y_reportes\duplicadoFacturaController))
#3 C:\xampp\htdocs\web\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\web\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-05-09 22:34:51 --> Undefined array key "id_usuario"
#0 C:\xampp\htdocs\web\app\Controllers\consultas_y_reportes\duplicadoFacturaController.php(23): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array...', 'C:\\xampp\\htdocs...', 23)
#1 C:\xampp\htdocs\web\system\CodeIgniter.php(832): App\Controllers\consultas_y_reportes\duplicadoFacturaController->facturas_por_rango_de_fechas()
#2 C:\xampp\htdocs\web\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\consultas_y_reportes\duplicadoFacturaController))
#3 C:\xampp\htdocs\web\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\web\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-05-09 22:36:09 --> Undefined array key "id_usuario"
#0 C:\xampp\htdocs\web\app\Controllers\consultas_y_reportes\duplicadoFacturaController.php(23): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array...', 'C:\\xampp\\htdocs...', 23)
#1 C:\xampp\htdocs\web\system\CodeIgniter.php(832): App\Controllers\consultas_y_reportes\duplicadoFacturaController->facturas_por_rango_de_fechas()
#2 C:\xampp\htdocs\web\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\consultas_y_reportes\duplicadoFacturaController))
#3 C:\xampp\htdocs\web\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\web\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-05-09 22:36:54 --> Undefined array key "id_usuario"
#0 C:\xampp\htdocs\web\app\Controllers\consultas_y_reportes\duplicadoFacturaController.php(23): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array...', 'C:\\xampp\\htdocs...', 23)
#1 C:\xampp\htdocs\web\system\CodeIgniter.php(832): App\Controllers\consultas_y_reportes\duplicadoFacturaController->facturas_por_rango_de_fechas()
#2 C:\xampp\htdocs\web\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\consultas_y_reportes\duplicadoFacturaController))
#3 C:\xampp\htdocs\web\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\web\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-05-09 22:36:58 --> Undefined array key "id_usuario"
#0 C:\xampp\htdocs\web\app\Controllers\consultas_y_reportes\duplicadoFacturaController.php(23): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array...', 'C:\\xampp\\htdocs...', 23)
#1 C:\xampp\htdocs\web\system\CodeIgniter.php(832): App\Controllers\consultas_y_reportes\duplicadoFacturaController->facturas_por_rango_de_fechas()
#2 C:\xampp\htdocs\web\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\consultas_y_reportes\duplicadoFacturaController))
#3 C:\xampp\htdocs\web\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\web\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-05-09 22:37:05 --> Undefined array key "id_usuario"
#0 C:\xampp\htdocs\web\app\Controllers\consultas_y_reportes\duplicadoFacturaController.php(23): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array...', 'C:\\xampp\\htdocs...', 23)
#1 C:\xampp\htdocs\web\system\CodeIgniter.php(832): App\Controllers\consultas_y_reportes\duplicadoFacturaController->facturas_por_rango_de_fechas()
#2 C:\xampp\htdocs\web\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\consultas_y_reportes\duplicadoFacturaController))
#3 C:\xampp\htdocs\web\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\web\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-05-09 22:37:06 --> Undefined array key "id_usuario"
#0 C:\xampp\htdocs\web\app\Controllers\consultas_y_reportes\duplicadoFacturaController.php(23): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array...', 'C:\\xampp\\htdocs...', 23)
#1 C:\xampp\htdocs\web\system\CodeIgniter.php(832): App\Controllers\consultas_y_reportes\duplicadoFacturaController->facturas_por_rango_de_fechas()
#2 C:\xampp\htdocs\web\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\consultas_y_reportes\duplicadoFacturaController))
#3 C:\xampp\htdocs\web\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\web\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-05-09 22:37:06 --> Undefined array key "id_usuario"
#0 C:\xampp\htdocs\web\app\Controllers\consultas_y_reportes\duplicadoFacturaController.php(23): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array...', 'C:\\xampp\\htdocs...', 23)
#1 C:\xampp\htdocs\web\system\CodeIgniter.php(832): App\Controllers\consultas_y_reportes\duplicadoFacturaController->facturas_por_rango_de_fechas()
#2 C:\xampp\htdocs\web\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\consultas_y_reportes\duplicadoFacturaController))
#3 C:\xampp\htdocs\web\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\web\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-05-09 22:37:06 --> Undefined array key "id_usuario"
#0 C:\xampp\htdocs\web\app\Controllers\consultas_y_reportes\duplicadoFacturaController.php(23): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array...', 'C:\\xampp\\htdocs...', 23)
#1 C:\xampp\htdocs\web\system\CodeIgniter.php(832): App\Controllers\consultas_y_reportes\duplicadoFacturaController->facturas_por_rango_de_fechas()
#2 C:\xampp\htdocs\web\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\consultas_y_reportes\duplicadoFacturaController))
#3 C:\xampp\htdocs\web\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\web\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-05-09 22:37:06 --> Undefined array key "id_usuario"
#0 C:\xampp\htdocs\web\app\Controllers\consultas_y_reportes\duplicadoFacturaController.php(23): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array...', 'C:\\xampp\\htdocs...', 23)
#1 C:\xampp\htdocs\web\system\CodeIgniter.php(832): App\Controllers\consultas_y_reportes\duplicadoFacturaController->facturas_por_rango_de_fechas()
#2 C:\xampp\htdocs\web\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\consultas_y_reportes\duplicadoFacturaController))
#3 C:\xampp\htdocs\web\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\web\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-05-09 22:37:07 --> Undefined array key "id_usuario"
#0 C:\xampp\htdocs\web\app\Controllers\consultas_y_reportes\duplicadoFacturaController.php(23): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array...', 'C:\\xampp\\htdocs...', 23)
#1 C:\xampp\htdocs\web\system\CodeIgniter.php(832): App\Controllers\consultas_y_reportes\duplicadoFacturaController->facturas_por_rango_de_fechas()
#2 C:\xampp\htdocs\web\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\consultas_y_reportes\duplicadoFacturaController))
#3 C:\xampp\htdocs\web\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\web\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-05-09 22:37:07 --> Undefined array key "id_usuario"
#0 C:\xampp\htdocs\web\app\Controllers\consultas_y_reportes\duplicadoFacturaController.php(23): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array...', 'C:\\xampp\\htdocs...', 23)
#1 C:\xampp\htdocs\web\system\CodeIgniter.php(832): App\Controllers\consultas_y_reportes\duplicadoFacturaController->facturas_por_rango_de_fechas()
#2 C:\xampp\htdocs\web\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\consultas_y_reportes\duplicadoFacturaController))
#3 C:\xampp\htdocs\web\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\web\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-05-09 22:37:28 --> Undefined array key "id_usuario"
#0 C:\xampp\htdocs\web\app\Controllers\consultas_y_reportes\duplicadoFacturaController.php(23): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array...', 'C:\\xampp\\htdocs...', 23)
#1 C:\xampp\htdocs\web\system\CodeIgniter.php(832): App\Controllers\consultas_y_reportes\duplicadoFacturaController->facturas_por_rango_de_fechas()
#2 C:\xampp\htdocs\web\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\consultas_y_reportes\duplicadoFacturaController))
#3 C:\xampp\htdocs\web\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\web\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-05-09 22:38:08 --> Undefined array key "id_usuario"
#0 C:\xampp\htdocs\web\app\Controllers\consultas_y_reportes\duplicadoFacturaController.php(23): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array...', 'C:\\xampp\\htdocs...', 23)
#1 C:\xampp\htdocs\web\system\CodeIgniter.php(832): App\Controllers\consultas_y_reportes\duplicadoFacturaController->facturas_por_rango_de_fechas()
#2 C:\xampp\htdocs\web\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\consultas_y_reportes\duplicadoFacturaController))
#3 C:\xampp\htdocs\web\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\web\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-05-09 22:40:28 --> Undefined array key "id_usuario"
#0 C:\xampp\htdocs\web\app\Controllers\consultas_y_reportes\duplicadoFacturaController.php(23): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array...', 'C:\\xampp\\htdocs...', 23)
#1 C:\xampp\htdocs\web\system\CodeIgniter.php(832): App\Controllers\consultas_y_reportes\duplicadoFacturaController->facturas_por_rango_de_fechas()
#2 C:\xampp\htdocs\web\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\consultas_y_reportes\duplicadoFacturaController))
#3 C:\xampp\htdocs\web\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\web\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-05-09 22:40:42 --> Undefined array key "id_usuario"
#0 C:\xampp\htdocs\web\app\Controllers\consultas_y_reportes\duplicadoFacturaController.php(23): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array...', 'C:\\xampp\\htdocs...', 23)
#1 C:\xampp\htdocs\web\system\CodeIgniter.php(832): App\Controllers\consultas_y_reportes\duplicadoFacturaController->facturas_por_rango_de_fechas()
#2 C:\xampp\htdocs\web\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\consultas_y_reportes\duplicadoFacturaController))
#3 C:\xampp\htdocs\web\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\web\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-05-09 22:42:09 --> Undefined array key "id_usuario"
#0 C:\xampp\htdocs\web\app\Controllers\consultas_y_reportes\duplicadoFacturaController.php(23): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array...', 'C:\\xampp\\htdocs...', 23)
#1 C:\xampp\htdocs\web\system\CodeIgniter.php(832): App\Controllers\consultas_y_reportes\duplicadoFacturaController->facturas_por_rango_de_fechas()
#2 C:\xampp\htdocs\web\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\consultas_y_reportes\duplicadoFacturaController))
#3 C:\xampp\htdocs\web\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\web\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-05-09 22:43:22 --> Undefined array key "id_usuario"
#0 C:\xampp\htdocs\web\app\Controllers\consultas_y_reportes\duplicadoFacturaController.php(23): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array...', 'C:\\xampp\\htdocs...', 23)
#1 C:\xampp\htdocs\web\system\CodeIgniter.php(832): App\Controllers\consultas_y_reportes\duplicadoFacturaController->facturas_por_rango_de_fechas()
#2 C:\xampp\htdocs\web\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\consultas_y_reportes\duplicadoFacturaController))
#3 C:\xampp\htdocs\web\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\web\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-05-09 22:43:42 --> Undefined array key "id_usuario"
#0 C:\xampp\htdocs\web\app\Controllers\consultas_y_reportes\duplicadoFacturaController.php(23): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array...', 'C:\\xampp\\htdocs...', 23)
#1 C:\xampp\htdocs\web\system\CodeIgniter.php(832): App\Controllers\consultas_y_reportes\duplicadoFacturaController->facturas_por_rango_de_fechas()
#2 C:\xampp\htdocs\web\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\consultas_y_reportes\duplicadoFacturaController))
#3 C:\xampp\htdocs\web\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\web\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-05-09 22:44:16 --> Undefined array key "id_usuario"
#0 C:\xampp\htdocs\web\app\Controllers\consultas_y_reportes\duplicadoFacturaController.php(23): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array...', 'C:\\xampp\\htdocs...', 23)
#1 C:\xampp\htdocs\web\system\CodeIgniter.php(832): App\Controllers\consultas_y_reportes\duplicadoFacturaController->facturas_por_rango_de_fechas()
#2 C:\xampp\htdocs\web\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\consultas_y_reportes\duplicadoFacturaController))
#3 C:\xampp\htdocs\web\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\web\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-05-09 22:44:17 --> Undefined array key "id_usuario"
#0 C:\xampp\htdocs\web\app\Controllers\consultas_y_reportes\duplicadoFacturaController.php(23): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array...', 'C:\\xampp\\htdocs...', 23)
#1 C:\xampp\htdocs\web\system\CodeIgniter.php(832): App\Controllers\consultas_y_reportes\duplicadoFacturaController->facturas_por_rango_de_fechas()
#2 C:\xampp\htdocs\web\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\consultas_y_reportes\duplicadoFacturaController))
#3 C:\xampp\htdocs\web\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\web\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-05-09 22:47:30 --> Undefined array key "id_usuario"
#0 C:\xampp\htdocs\web\app\Controllers\consultas_y_reportes\duplicadoFacturaController.php(23): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array...', 'C:\\xampp\\htdocs...', 23)
#1 C:\xampp\htdocs\web\system\CodeIgniter.php(832): App\Controllers\consultas_y_reportes\duplicadoFacturaController->facturas_por_rango_de_fechas()
#2 C:\xampp\htdocs\web\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\consultas_y_reportes\duplicadoFacturaController))
#3 C:\xampp\htdocs\web\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\web\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-05-09 22:48:09 --> Undefined array key "id_usuario"
#0 C:\xampp\htdocs\web\app\Controllers\consultas_y_reportes\duplicadoFacturaController.php(23): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array...', 'C:\\xampp\\htdocs...', 23)
#1 C:\xampp\htdocs\web\system\CodeIgniter.php(832): App\Controllers\consultas_y_reportes\duplicadoFacturaController->facturas_por_rango_de_fechas()
#2 C:\xampp\htdocs\web\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\consultas_y_reportes\duplicadoFacturaController))
#3 C:\xampp\htdocs\web\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\web\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-05-09 22:50:07 --> Undefined array key "id_usuario"
#0 C:\xampp\htdocs\web\app\Controllers\consultas_y_reportes\duplicadoFacturaController.php(23): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array...', 'C:\\xampp\\htdocs...', 23)
#1 C:\xampp\htdocs\web\system\CodeIgniter.php(832): App\Controllers\consultas_y_reportes\duplicadoFacturaController->facturas_por_rango_de_fechas()
#2 C:\xampp\htdocs\web\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\consultas_y_reportes\duplicadoFacturaController))
#3 C:\xampp\htdocs\web\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\web\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-05-09 22:50:38 --> Undefined array key "id_usuario"
#0 C:\xampp\htdocs\web\app\Controllers\consultas_y_reportes\duplicadoFacturaController.php(23): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array...', 'C:\\xampp\\htdocs...', 23)
#1 C:\xampp\htdocs\web\system\CodeIgniter.php(832): App\Controllers\consultas_y_reportes\duplicadoFacturaController->facturas_por_rango_de_fechas()
#2 C:\xampp\htdocs\web\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\consultas_y_reportes\duplicadoFacturaController))
#3 C:\xampp\htdocs\web\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\web\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-05-09 22:51:42 --> Undefined array key "id_usuario"
#0 C:\xampp\htdocs\web\app\Controllers\consultas_y_reportes\duplicadoFacturaController.php(23): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array...', 'C:\\xampp\\htdocs...', 23)
#1 C:\xampp\htdocs\web\system\CodeIgniter.php(832): App\Controllers\consultas_y_reportes\duplicadoFacturaController->facturas_por_rango_de_fechas()
#2 C:\xampp\htdocs\web\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\consultas_y_reportes\duplicadoFacturaController))
#3 C:\xampp\htdocs\web\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\web\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-05-09 22:53:24 --> Undefined array key "id_usuario"
#0 C:\xampp\htdocs\web\app\Controllers\consultas_y_reportes\duplicadoFacturaController.php(23): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array...', 'C:\\xampp\\htdocs...', 23)
#1 C:\xampp\htdocs\web\system\CodeIgniter.php(832): App\Controllers\consultas_y_reportes\duplicadoFacturaController->facturas_por_rango_de_fechas()
#2 C:\xampp\htdocs\web\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\consultas_y_reportes\duplicadoFacturaController))
#3 C:\xampp\htdocs\web\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\web\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-05-09 23:32:26 --> Undefined array key "fecha_inicial"
#0 C:\xampp\htdocs\web\app\Controllers\consultas_y_reportes\duplicadoFacturaController.php(21): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array...', 'C:\\xampp\\htdocs...', 21)
#1 C:\xampp\htdocs\web\system\CodeIgniter.php(832): App\Controllers\consultas_y_reportes\duplicadoFacturaController->facturas_por_rango_de_fechas()
#2 C:\xampp\htdocs\web\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\consultas_y_reportes\duplicadoFacturaController))
#3 C:\xampp\htdocs\web\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\web\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
